export default {
  ADD_ROUTE_INFO:'ADD_ROUTE_INFO',
  LOGIN_TOGGLE:'LOGIN_TOGGLE',
  LOGIN_ADD:'LOGIN_ADD',
  LOGIN_CLEAR:'LOGIN_CLEAR',
  LOAD_MYFICTION:'LOAD_MYFICTION',
  MYFICTION_LOADING:'MYFICTION_LOADING',
  LOAD_MYFICTION_BY_TITLE:'LOAD_MYFICTION_BY_TITLE',
  MYFICTION_WRITE_CONTENT:'MYFICTION_WRITE_CONTENT',
  MYFICTION_INIT_FORM_ADD:'MYFICTION_INIT_FORM_ADD',
  SET_CURRENT_URL:'SET_CURRENT_URL',
  UPDATE_AMT_VIEWERS:'UPDATE_AMT_VIEWERS'
  
}